apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: selfsigned
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: selfsigned-ca
spec:
  commonName: Self-Signed CA
  secretName: selfsigned-ca
  isCA: true
  issuerRef:
    name: selfsigned
    kind: Issuer
    group: cert-manager.io
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: selfsigned-ca
spec:
  ca:
    secretName: selfsigned-ca
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: custom-cert
spec:
  commonName: openldap-stack-ha.default.svc
  dnsNames:
    - "openldap-stack-ha.default.svc"
    - "openldap-stack-ha.default.svc.cluster.local"
    - "*.openldap-stack-ha-headless.default.svc.cluster.local"
  secretName: custom-cert
  issuerRef:
    name: selfsigned-ca
    kind: Issuer
    group: cert-manager.io