name: Setup
on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "master"
      - "bitnami"
jobs:
  call-ci-singlenode:
    uses: ./.github/workflows/ci-singlenode.yml
  call-ci-other:
    uses: ./.github/workflows/ci-other.yml
  call-ci-ha:
    uses: ./.github/workflows/ci-ha.yml
  call-ci-readonly:
    uses: ./.github/workflows/ci-readonly.yml